apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opspvc
  namespace: kube-ops
  labels:
    app: jenkins2
spec:
  storageClassName: static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
