apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-local
  namespace: kube-ops
  labels:
    type: local
spec:
  storageClassName: static
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host/ubuntu_root/data/local_data/"
